"""
project_files.py
------------------
Static text content (README, requirements.txt, package.json) reused both by
the actual repo files on disk AND by the Streamlit app's download buttons,
so the downloaded copies always match what's checked into the repo.
"""

README_CONTENT = """# Local Quiz Generator (Ollama + qwen3:4b)

A fully offline chatbot that generates multiple-choice quizzes from an
uploaded Word (.docx) or PDF (.pdf) document, using a local Ollama model.
No cloud API calls, no API keys — everything runs on your machine.

## Requirements

- Python 3.10+
- [Ollama](https://ollama.com) installed and running locally
- ~8GB RAM is enough for `qwen3:4b` (a small, quantized model)

## Setup

1. Install Ollama and pull the model:
   ```bash
   ollama pull qwen3:4b
   ollama serve
   ```
   (Keep `ollama serve` running in a terminal — the app talks to it over
   `http://localhost:11434`.)

2. Install Python dependencies:
   ```bash
   pip install -r requirements.txt
   ```

3. Run the app:
   ```bash
   streamlit run app.py
   ```
   This opens the chatbot in your browser (usually http://localhost:8501).

## Using the app

1. Upload a `.docx` or `.pdf` file.
2. In the sidebar, set:
   - Number of questions
   - Number of options per question
   - Option label style (alphabetic A/B/C or roman numeral I/II/III)
3. Click **Generate Quiz**.
4. Review the generated questions, then use the download buttons to save:
   - A standalone quiz-runner script (Python or JS, no dependencies needed to run it)
   - This README
   - `requirements.txt` (or `package.json` if you chose JS)
   - The raw quiz as JSON

## Running the downloaded quiz script standalone

The downloaded `quiz_runner.py` / `quiz_runner.js` has the quiz data
embedded directly in it — it does not need this app or Ollama to run.

```bash
python quiz_runner.py
# or
node quiz_runner.js
```

## Troubleshooting on low-RAM machines

- **Generation is slow / times out:** close other memory-heavy apps.
  CPU-only generation on an i5 with 8GB RAM is expected to take anywhere
  from several seconds to a couple of minutes per batch of questions,
  depending on document length.
- **"Could not reach Ollama":** make sure `ollama serve` is running and
  that the model was pulled (`ollama pull qwen3:4b`).
- **Fewer questions generated than requested:** the source document may be
  too short, or the model produced malformed output for some chunks (this
  is shown as a warning in the app rather than failing silently).
- **Large documents:** the app automatically splits long documents into
  smaller chunks (~900 words each) before sending them to the model, to
  avoid overloading memory and the model's context window.

## Project structure

```
app.py                      # Streamlit UI
quiz_generator.py           # Ollama calls, prompt building, JSON parsing
file_parser.py               # docx/pdf text extraction + chunking
standalone_script_builder.py # Generates the downloadable quiz-runner script
project_files.py             # README / requirements / package.json content
requirements.txt
package.json                 # Only needed if you use the JS quiz-runner output
.env.example
.gitignore
```

## Configuration

Copy `.env.example` to `.env` (or just set these as environment variables)
to change defaults:

```
OLLAMA_HOST=http://localhost:11434
OLLAMA_MODEL=qwen3:4b
CHUNK_WORD_SIZE=900
OLLAMA_TIMEOUT=180
```
"""

REQUIREMENTS_TXT = """streamlit>=1.35
requests>=2.31
python-docx>=1.1
pdfplumber>=0.11
PyPDF2>=3.0
"""

PACKAGE_JSON = """{
  "name": "quiz-runner",
  "version": "1.0.0",
  "description": "Standalone offline quiz runner generated by the Local Quiz Generator app.",
  "main": "quiz_runner.js",
  "scripts": {
    "start": "node quiz_runner.js"
  },
  "license": "MIT"
}
"""
